### ISSUE TITLE
I don't know how to use pato to pick the real DNA: RNA triplexator.

### ISSUE THREAD

**Issue by jkvoivp** [UDC-GAC/PATO#9]
Dear authours,
When I ran PATO's tests, I only find interaction pairs in the tpx.n.par.out file, but it contains non-real interaction pairs. In the output files, The first question I don't know what the TFO and TTS files do,how can I use them?. Second, how did I use these files to find relatively reliable DNA: RNA Triplexator?
I'm looking forward to your reply, thank you.

**Comment by amatria** [comment]
Hi @jkvoivp 

With regard to the tests, ignore the interactions you get there. The interactions in the test files are synthetic and only exist to detect regressions in the software (i.e., to detect if a new commit changes the functioning of PATO). 

Now, concerning the TFO and TTS files, those are files that you get when you respectively analyze a single stranded sequence file (i.e., `pato -ss single_stranded.fa`) and a double stranded sequence file (i.e., `pato -ds double_stranded.fa`). And these files hold TFO or TTS regions in the sequences that may be likely to form a triplex. However, if you want to predict triple helices that may form between a single stranded sequence file and a double stranded sequence file, you must tell PATO to match their TFO and TTS regions (i.e., execute `pato -ss single_stranded.fa -ds double_stranded.fa`). After you do that, you will get two output files:
- `pato.out` will hold all the individual triple helices that were found between the sequences in the single stranded file and the sequences in the double stranded file.
- `pato.summary` will hold the interaction strength between each sequence in the single stranded file and each sequence in the double stranded file.

If you want to select candidate triplexes reliably, sort the interacting pairs in `pato.summary` with respect to their interaction strength (i.e., column `Total (rel)`), and study the triplexes found between those two sequences.

I hope this helps :).

And if you believe this information is of good interest, I could add it to the README file. Just let le know.

**Comment by amatria** [comment]
Also, I recommended papers such as https://doi.org/10.3390/ijms21030830 if you want to increase your odds of finding more reliable triplexes by fine tuning the search parameters of PATO

**Comment by jkvoivp** [comment]
Thank you very much for your reply, with your helpful advices I successfully got the results, thank you, I wish you have a sweeter life.

**Comment by amatria** [comment]
I'm glad I could help :)

**Comment by amatria** [comment]
https://github.com/UDC-GAC/PATO/commit/0bad52bdf3c99551c2f164a5e0974f3e18eaf9fe adds this exact information to the README
